# Generated by Django 4.0.4 on 2022-06-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
